<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <!-- Limit .NET Framework tests to Windows build / test machines -->
    <TargetFrameworks Condition="'$(OS)' == 'Windows_NT'">net472</TargetFrameworks>
    <TargetFrameworks>$(TargetFrameworks);net8.0;net9.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <!-- Allow downgrade of System.Text.Json to 8.0.x for net472 compatibility. Remove this once STJ is resolved. -->
    <NoWarn>$(NoWarn);NU1605;NU1109</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="MSBuild.ProjectCreation" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Extensions" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" />
    <PackageReference Include="Verify.MSTest" />
    <PackageReference Include="GetPackFromProject" PrivateAssets="all" />
    <ProjectReference Include="..\..\Verify.Nupkg\Verify.Nupkg.csproj" AddPackageAsOutput="true" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <!--
      Pin System.Text.Json to 8.0.x on net472, as NuGet.Packaging requires 8.x and Microsoft.Build pulls in 9.x
    -->
    <PackageReference Include="System.Text.Encodings.Web" VersionOverride="8.0.0" />
    <PackageReference Include="System.Text.Json" VersionOverride="8.0.5" />
  </ItemGroup>

  <!--
    TODO: This should happen automatically when including Verify.
    Unclear why this needs to be added manually in this case.
  -->
  <ItemGroup>
    <None Update="**\*.received.*;**\*.verified.*" Condition="$(Language) == 'C#'">
      <ParentFile>$([System.String]::Copy('%(FileName)').Split('.')[0].Split('(')[0])</ParentFile>
      <DependentUpon>%(ParentFile).cs</DependentUpon>
    </None>
  </ItemGroup>
</Project>
